spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: la
      auto-index-creation: true
      uuid-representation: standard
      field-naming-strategy: org.springframework.data.mapping.model.SnakeCaseFieldNamingStrategy